# Config Repository: api-gateway.yml (FINAL CORRECT VERSION)

server:
  port: 9090

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false 
      routes:
        # Start of Route Definition
        - id: user_route
          uri: lb://USER-SERVICE 
          # Separate section for predicates
          predicates:
            - Path=/user/** # Separate section for filters, MUST align with 'predicates' and 'uri'
          filters:
            - StripPrefix=1
        # NEW ROUTE FOR JOB SERVICE
        - id: job_route
          uri: lb://JOB-SERVICE
          predicates:
            - Path=/job/**
          filters:
            - StripPrefix=1
        # 3. Bidding Service (Make sure this is here!)
        - id: bidding_route
          uri: lb://BIDDING-SERVICE
          predicates:
            - Path=/bid/**
          filters:
            - StripPrefix=1