server:
  port: 8083

spring:
  application:
    name: bidding-service
  
  datasource:
    url: jdbc:h2:mem:skillhub_bidding_db;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

  # RABBITMQ CONFIGURATION (New)
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/