# skillhub-config/user-service.yml
server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:skillhub_user_db;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # Automatically creates tables based on Entities
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console